# Generated by Django 5.1.4 on 2024-12-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='iv',
            field=models.CharField(default='default_value', max_length=255),
        ),
    ]
